name: docbuilder
version: '0.1.0'
author: Scott Murphy <scottmurphy09@gmail.com>
maintainer: Scott Murphy <scottmurphy09@gmail.com>
license: BSD3
git: 'https://github.com/plow-technologies/docbuilder.git'
dependencies:  
  - base            >= 4 && <5
  - system-fileio   >= 0.3.15
  - system-filepath >= 0.4.12
  - shake
  - haddock-api
  - text
  - time
  - yaml
  - lens-aeson
  - hxt
  - aeson
  - lens
  - lens-regex
  - regex-posix
library:
  source-dirs: src
  ghc-options: -Wall
  exposed-modules:
    - System.Docbuilder
    - System.Docbuilder.Hxt
executables:
  docbuilder:
    main: Main.hs
    source-dirs:  src
    ghc-options: -Wall


tests:
  spec:
    main: Spec.hs
    source-dirs:
    - src
    - test
    ghc-options: -Wall
    dependencies:

